#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag nandiheath/tvhk-peertube nandiheath/tvhk-peertube:$TRAVIS_COMMIT
docker push nandiheath/tvhk-peertube:$TRAVIS_COMMIT